import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adri Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Adri Tasks es una aplicación poderosa de gestión de tareas diseñada para ayudarte a organizar y priorizar tu trabajo de manera eficiente. ¡Mejora tu productividad ahora!"
        />
        <meta
          name="keywords"
          content="gestión de tareas, productividad, lista de tareas, organizar tareas, Adri Tasks"
        />
        <meta name="author" content="Equipo de Adri Tasks" />
        <meta name="robots" content="index, follow" />
        <link rel="icon" href="/logo2.svg" />

        <meta
          property="og:title"
          content="Adri Tasks - Administra tus tareas de manera eficiente"
        />
        <meta
          property="og:description"
          content="Adri Tasks es una aplicación de gestión de tareas diseñada para mejorar tu productividad organizando y priorizando tareas. ¡Empieza a gestionar tus tareas hoy!"
        />
        <meta property="og:image" content="/logo2.svg" />
        <meta
          property="og:url"
          content="https://next-track-three.vercel.app/"
        />
        <meta property="og:type" content="website" />

        <title>Adri Tasks - Administra tus tareas de manera eficiente</title>
      </head>

      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <QueryProvider>
            <Toaster />
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
